/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Clientes;
import Classes.ContasReceber;
import Classes.DateTime;
import Classes.Empresa;
import Classes.Itemvendido;
import Classes.Produto;
import Classes.Venda;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Vinicius
 */
public class JDialogPagamentoCR extends javax.swing.JDialog {

    /**
     * Creates new form JDialogPagamento
     */
    private JTable TabelaA, TabelaB;
    private String CPF;
    private int CodVendedor;
    private float CR_Total; // armazena total da venda e compra respectivamente

    /**
     * Construtor para escolher forma de pagamento de contas a receber
     */
    public JDialogPagamentoCR(javax.swing.JDialog parent, boolean modal, JTable TabelaA, JTable TabelaB, String CPF, int CodVendedor, float CR_Total) {
        super(parent, modal);
        initComponents();

        jComboBoxCR_Parcelas.setEnabled(false);
        jListCR_Parcelas.setEnabled(false);
        jButtonCR_FinalizarParcelas.setEnabled(false);

        
        jTabbedPaneCR_Pagamento.setEnabledAt(1, false);
        jTabbedPaneCR_Pagamento.setSelectedIndex(0);

        jTextFieldCR_Valor.setEnabled(false);
        jLabelCR_Total.setText("" + CR_Total);
        jButtonCR_FinalizarPagVista.setEnabled(false);

        this.TabelaA = TabelaA;
        this.TabelaB = TabelaB;
        this.CPF = CPF;
        this.CodVendedor = CodVendedor;
        this.CR_Total = CR_Total;
    }

    /**
     * Construtor para efetuar pagamento de contas a receber
     */
    public JDialogPagamentoCR(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jTabbedPaneCR_Pagamento.setEnabledAt(0, false);
        jButtonCR_FinalizarPagamento.setEnabled(false);
        jTabbedPaneCR_Pagamento.setSelectedIndex(1);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        jTabbedPaneCR_Pagamento = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCR_Parcelas = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCR_Parcelas = new javax.swing.JComboBox();
        jButtonCR_FinalizarParcelas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCR_Troco = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelAviso = new javax.swing.JLabel();
        jTextFieldCR_Valor = new javax.swing.JTextField();
        jButtonCR_FinalizarPagVista = new javax.swing.JButton();
        jComboBoxCR_Escolha = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabelCR_Total = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelCR_Valor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelCR_DataV = new javax.swing.JLabel();
        jLabelCR_Status = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelCR_NParcela = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabelCR_TrocoP = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelCR_AvisoP = new javax.swing.JLabel();
        jTextFieldCR_ValorP = new javax.swing.JTextField();
        jButtonCR_FinalizarPagamento = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonCR_Localizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCR_CodParcela = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCR_CodCompra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabelCR_Nome = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelCR_Prestantes = new javax.swing.JLabel();
        jLabelCR_QtdParcela = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma de pagamento");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Parcelado"));

        jScrollPane1.setViewportView(jListCR_Parcelas);

        jLabel3.setText("Numero de parcelas");

        jComboBoxCR_Parcelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jButtonCR_FinalizarParcelas.setText("Finalizar");
        jButtonCR_FinalizarParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCR_FinalizarParcelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCR_Parcelas, 0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCR_FinalizarParcelas)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxCR_Parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButtonCR_FinalizarParcelas)
                .addContainerGap())
        );

        jLabel1.setText("Forma de pagamento:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "À Vista"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Valor pago: R$");

        jLabelCR_Troco.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCR_Troco.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Troco:       R$");

        jLabelAviso.setForeground(new java.awt.Color(255, 0, 0));
        jLabelAviso.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jTextFieldCR_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCR_ValorActionPerformed(evt);
            }
        });
        jTextFieldCR_Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCR_ValorKeyReleased(evt);
            }
        });

        jButtonCR_FinalizarPagVista.setText("Finalizar");
        jButtonCR_FinalizarPagVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCR_FinalizarPagVistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCR_Valor)
                            .addComponent(jLabelCR_Troco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCR_FinalizarPagVista)))
                    .addComponent(jLabelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCR_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCR_Troco, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCR_FinalizarPagVista)
                .addContainerGap())
        );

        jComboBoxCR_Escolha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione forma de pagamento", "À vista", "Parcelado" }));
        jComboBoxCR_Escolha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxCR_EscolhaMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCR_EscolhaMouseClicked(evt);
            }
        });
        jComboBoxCR_Escolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCR_EscolhaActionPerformed(evt);
            }
        });
        jComboBoxCR_Escolha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBoxCR_EscolhaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Valor da compra:  R$");

        jLabelCR_Total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCR_Total.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCR_Total.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCR_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCR_Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCR_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCR_Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2});

        jTabbedPaneCR_Pagamento.addTab("Forma de pagamento", jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Parcela"));

        jLabelCR_Valor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Valor:");

        jLabelCR_DataV.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCR_Status.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Status Parcela:");

        jLabel8.setText("Data vencimento:");

        jLabel11.setText("Numero da Parcela:");

        jLabelCR_NParcela.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCR_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCR_Valor, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabelCR_DataV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCR_NParcela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabelCR_DataV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCR_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabelCR_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCR_NParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Efetuar pagamento"));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Valor pago: R$");

        jLabelCR_TrocoP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCR_TrocoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Troco:       R$");

        jLabelCR_AvisoP.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCR_AvisoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jTextFieldCR_ValorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCR_ValorPActionPerformed(evt);
            }
        });
        jTextFieldCR_ValorP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCR_ValorPKeyReleased(evt);
            }
        });

        jButtonCR_FinalizarPagamento.setText("Finalizar");
        jButtonCR_FinalizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCR_FinalizarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelCR_AvisoP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCR_FinalizarPagamento))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabelCR_TrocoP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCR_ValorP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabelCR_AvisoP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCR_ValorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCR_TrocoP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCR_FinalizarPagamento)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCR_Localizar.setText("Localizar");
        jButtonCR_Localizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCR_LocalizarActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo da compra:");

        jLabel6.setText("Codigo da parcela:");

        jLabel16.setText("Cliente:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCR_CodCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldCR_CodParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCR_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCR_Localizar)))
                .addGap(16, 16, 16))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCR_CodParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCR_CodCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCR_Localizar)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelCR_Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Quantidades"));

        jLabelCR_Prestantes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCR_QtdParcela.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Parcelas restantes:");

        jLabel15.setText("Qtd Parcelas:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCR_Prestantes, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabelCR_QtdParcela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabelCR_QtdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCR_Prestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPaneCR_Pagamento.addTab("Efetuar pagamento", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jButtonSair))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPaneCR_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCR_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-501)/2, (screenSize.height-464)/2, 501, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCR_LocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCR_LocalizarActionPerformed
        ContasReceber Cr = new ContasReceber();
        if (Cr.BuscaParcela(Integer.parseInt(jTextFieldCR_CodCompra.getText()), Integer.parseInt(jTextFieldCR_CodParcela.getText()))) {
            jTextFieldCR_ValorP.setEnabled(true);
            jLabelCR_DataV.setText(Cr.getDataPrevista());
            jLabelCR_Valor.setText("" + Cr.getValorParcela());
            CPF = Cr.getCPF();

            //Mostrar o nome do cliente
            Clientes C = new Clientes();
            C.pesquisa(CPF);
            jLabelCR_Nome.setText(C.getNome());
            if (Cr.isStatus()) {
                jLabelCR_Status.setText("Pagada");
                jTextFieldCR_ValorP.setEnabled(false);
            } else {
                jLabelCR_Status.setText("À pagar");
                jTextFieldCR_ValorP.setEnabled(true);
            }
            jLabelCR_NParcela.setText("" + Integer.parseInt(jTextFieldCR_CodParcela.getText()));
            jLabelCR_QtdParcela.setText("" + Cr.getQtdParcelas());
            jLabelCR_Prestantes.setText("" + Cr.getParcelaPendentes());
        } else {
            jTextFieldCR_ValorP.setEnabled(false);
            JOptionPane.showMessageDialog(null, "A uma conta anterior à se pagar");
        }
    }//GEN-LAST:event_jButtonCR_LocalizarActionPerformed

    private void jButtonCR_FinalizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCR_FinalizarPagamentoActionPerformed
        Empresa E = new Empresa();
        E.Pesquisa();
        E.setSaldo(E.getSaldo() + Float.parseFloat(jLabelCR_Valor.getText()));
        E.setCNPJ(E.getCNPJ());
        if (E.EditarSaldo()) {
            ContasReceber Cr = new ContasReceber();
            Cr.PagarParcelas(Integer.parseInt(jTextFieldCR_CodCompra.getText()), Integer.parseInt(jTextFieldCR_CodParcela.getText()));
            JOptionPane.showMessageDialog(this, "Pagamento efetuado com sucesso");
            // debitar valorApagar do cliente;
            Clientes C = new Clientes();
            C.setValorDevido(CR_Total);
            C.EditarDebito(CPF, (-Float.parseFloat(jLabelCR_Valor.getText()))); // passar o valor como negativo para ser debitado
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ERRO: Pagamento não Finalizado");
        }

    }//GEN-LAST:event_jButtonCR_FinalizarPagamentoActionPerformed

    private void jTextFieldCR_ValorPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCR_ValorPKeyReleased
        float Valor, VPagar;

        VPagar = Float.parseFloat(jLabelCR_Valor.getText());
        try {
            jLabelCR_AvisoP.setText("");
            Valor = Float.parseFloat(jTextFieldCR_ValorP.getText());
            if ((Valor - VPagar) < 0) {
                jLabelCR_TrocoP.setText("Insuficiente");
                jButtonCR_FinalizarPagamento.setEnabled(false);
            } else {
                jLabelCR_TrocoP.setText("" + (Valor - VPagar));
                jButtonCR_FinalizarPagamento.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            jLabelCR_AvisoP.setText("Somente Numeros");
            jButtonCR_FinalizarPagamento.setEnabled(false);
            jTextFieldCR_ValorP.setText("");
        }
    }//GEN-LAST:event_jTextFieldCR_ValorPKeyReleased

    private void jTextFieldCR_ValorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCR_ValorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCR_ValorPActionPerformed

    private void jComboBoxCR_EscolhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxCR_EscolhaKeyReleased
    }//GEN-LAST:event_jComboBoxCR_EscolhaKeyReleased

    private void jComboBoxCR_EscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCR_EscolhaActionPerformed
        String Escolha = "" + jComboBoxCR_Escolha.getSelectedItem();
        if (Escolha.equals("À vista")) {
            jTextFieldCR_Valor.setEnabled(true);
            jButtonCR_FinalizarPagVista.setEnabled(true);

            jComboBoxCR_Parcelas.setEnabled(false);
            jListCR_Parcelas.setEnabled(false);
            jButtonCR_FinalizarParcelas.setEnabled(false);
        } else if (Escolha.equals("Parcelado")) {
            jTextFieldCR_Valor.setEnabled(false);
            jButtonCR_FinalizarPagVista.setEnabled(false);

            jComboBoxCR_Parcelas.setEnabled(true);
            jListCR_Parcelas.setEnabled(true);
            jButtonCR_FinalizarParcelas.setEnabled(true);
        } else {
            jTextFieldCR_Valor.setEnabled(false);
            jButtonCR_FinalizarPagVista.setEnabled(false);

            jComboBoxCR_Parcelas.setEnabled(false);
            jListCR_Parcelas.setEnabled(false);
            jButtonCR_FinalizarParcelas.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxCR_EscolhaActionPerformed

    private void jComboBoxCR_EscolhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCR_EscolhaMouseClicked
    }//GEN-LAST:event_jComboBoxCR_EscolhaMouseClicked

    private void jComboBoxCR_EscolhaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCR_EscolhaMouseReleased
    }//GEN-LAST:event_jComboBoxCR_EscolhaMouseReleased

    private void jButtonCR_FinalizarPagVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCR_FinalizarPagVistaActionPerformed
        Empresa E = new Empresa();

        Venda V = new Venda();
        V.setCPFClinte(CPF);
        V.setCodVendedor(CodVendedor);

        V.Salvar();
        E.Pesquisa();
        E.setCNPJ(E.getCNPJ());
        E.setSaldo(E.getSaldo() + CR_Total);
        if (E.EditarSaldo()) {
            JOptionPane.showMessageDialog(this, "Compra Finalizada com sucesso");
            DefaultTableModel Tab = (DefaultTableModel) TabelaB.getModel();
            Tab.setNumRows(0);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ERRO: Compra não Finalizada");
        }
    }//GEN-LAST:event_jButtonCR_FinalizarPagVistaActionPerformed

    private void jTextFieldCR_ValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCR_ValorKeyReleased
        float Valor;
        try {
            jLabelAviso.setText("");
            Valor = Float.parseFloat(jTextFieldCR_Valor.getText());
            if ((Valor - CR_Total) < 0) {
                jLabelCR_Troco.setText("Insuficiente");
            } else {
                jLabelCR_Troco.setText("" + (Valor - CR_Total));
            }
        } catch (NumberFormatException e) {
            jLabelAviso.setText("Somente Numeros");
            jTextFieldCR_Valor.setText("");
        }
    }//GEN-LAST:event_jTextFieldCR_ValorKeyReleased

    private void jTextFieldCR_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCR_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCR_ValorActionPerformed

    private void jButtonCR_FinalizarParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCR_FinalizarParcelasActionPerformed
        DefaultTableModel Tab = (DefaultTableModel) TabelaB.getModel();
        boolean Conf1 = false, Conf2 = true;

        int Parcelas = Integer.parseInt("" + jComboBoxCR_Parcelas.getSelectedItem());
        DateTime Dt = new DateTime();
        float Pl = CR_Total / Parcelas;

        // Salvando a venda
        Venda V = new Venda();
        V.setCPFClinte(CPF);
        V.setCodVendedor(CodVendedor);

        if (V.Salvar()) {
            Conf1 = true;
        } else {
            Conf2 = false;
        }
        //

        //Salvando os itemvendido
        Itemvendido I = new Itemvendido();
        V.ExisteCod(); // busca o ultimo codigo da venda
        for (int x = 0; x < Tab.getRowCount(); x++) {
            I.setCodVenda(V.getCodVenda());
            I.setCodProduto((Integer.parseInt("" + TabelaB.getValueAt(x, 0))));
            I.setQuantidade(Integer.parseInt("" + TabelaB.getValueAt(x, 2)));

            if (I.Salvar()) {
                Conf1 = true;
            } else {
                Conf2 = false;
            }
        }
        //

        // Primeira verificação: se não houver erro na venda salva as parcelas
        if (Conf1 && Conf2) {
            // Salvando em contas a receber
            ContasReceber Cr = new ContasReceber();
            Cr.setCPF(CPF);
            Cr.setData(Dt.GetDateString());
            Cr.setQtdParcelas(Parcelas);
            Cr.setValorCompra(CR_Total);

            if (Cr.Salvar()) {
                Conf1 = true;
            } else {
                Conf2 = false;
            }
            //

            // Salvando as parcelas
            Cr.ExisteCod(); // busca o ultimo codigo salvo, que é o da compra realizada
            Cr.setCodConta(Cr.getCodConta());
            DefaultListModel Model = new DefaultListModel();
            String D;
            for (int i = 1; i <= Parcelas; i++) {
                D = "" + Dt.SomarMes(i);
                Model.addElement("" + i + "º  " + D + " ..... R$ " + Pl);
                Cr.setCodParcela(i);
                Cr.setStatus(false);
                Cr.setDataPrevista(D);
                Cr.setValorParcela(Pl);

                if (Cr.SalvarPacelas()) {
                    Conf1 = true;
                } else {
                    Conf2 = false;
                }
            }
            jListCR_Parcelas.setModel(Model);// Mostra as parcelas no Jlist
            //

            //Segunda verificação: se não houver erro nas parcelas salva como debito do cliente
            if (Conf1 && Conf2) {

                // salvando debito do cliente
                Clientes C = new Clientes();

                if (C.EditarDebito(CPF, CR_Total)) {
                    Conf1 = true;
                } else {
                    Conf2 = false;
                }
                //

                //Terceira verificação: se não houver erro debito, finalizar
                if (Conf1 && Conf2) {
                    JOptionPane.showMessageDialog(this, "Compra Finalizada com sucesso\n"
                            + "Codigo da Compra: " + Cr.getCodConta() + ",\nNumero de Parcelas: " + Parcelas + ".");
                    Tab.setNumRows(0);
                } else {
                    erro();
                }
            } else {
                erro();
            }
        } else {
            erro();
        }
        // Bloqueando butoes
        jTextFieldCR_Valor.setEnabled(false);
        jButtonCR_FinalizarPagVista.setEnabled(false);
        jComboBoxCR_Parcelas.setEnabled(false);
        jButtonCR_FinalizarParcelas.setEnabled(false);
        jComboBoxCR_Escolha.setEnabled(false);
        //
    }//GEN-LAST:event_jButtonCR_FinalizarParcelasActionPerformed

    public void erro() {
        DefaultTableModel Tab = (DefaultTableModel) TabelaB.getModel();

        // retorna os dados para o banco
        Produto P = new Produto();
        JOptionPane.showMessageDialog(this, "ERRO: Compra não Finalizada");
        for (int x = 0; x < Tab.getRowCount(); x++) {
            P.setCodProduto(Integer.parseInt("" + TabelaB.getValueAt(x, 0)));
            P.PesquisaCodigo();
            P.setQtdProduto(P.getQtdProduto() + Integer.parseInt("" + TabelaB.getValueAt(x, 2)));
            P.Alterar();
            Tab.removeRow(x);
        }
        Produto.carregaTabela(TabelaA, true); // chama carrega tabela excluido produtos sem quantidade
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
     /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     *
     try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(JDialogPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(JDialogPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(JDialogPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(JDialogPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the dialog *
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     JDialogPagamento dialog = new JDialogPagamento(new javax.swing.JFrame(), true);
     dialog.addWindowListener(new java.awt.event.WindowAdapter() {
     @Override
     public void windowClosing(java.awt.event.WindowEvent e) {
     System.exit(0);
     }
     });
     dialog.setVisible(true);
     }
     });
     }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCR_FinalizarPagVista;
    private javax.swing.JButton jButtonCR_FinalizarPagamento;
    private javax.swing.JButton jButtonCR_FinalizarParcelas;
    private javax.swing.JButton jButtonCR_Localizar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxCR_Escolha;
    private javax.swing.JComboBox jComboBoxCR_Parcelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelCR_AvisoP;
    private javax.swing.JLabel jLabelCR_DataV;
    private javax.swing.JLabel jLabelCR_NParcela;
    private javax.swing.JLabel jLabelCR_Nome;
    private javax.swing.JLabel jLabelCR_Prestantes;
    private javax.swing.JLabel jLabelCR_QtdParcela;
    private javax.swing.JLabel jLabelCR_Status;
    private javax.swing.JLabel jLabelCR_Total;
    private javax.swing.JLabel jLabelCR_Troco;
    private javax.swing.JLabel jLabelCR_TrocoP;
    private javax.swing.JLabel jLabelCR_Valor;
    private javax.swing.JList jListCR_Parcelas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneCR_Pagamento;
    private javax.swing.JTextField jTextFieldCR_CodCompra;
    private javax.swing.JTextField jTextFieldCR_CodParcela;
    private javax.swing.JTextField jTextFieldCR_Valor;
    private javax.swing.JTextField jTextFieldCR_ValorP;
    // End of variables declaration//GEN-END:variables
}
