/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.ContasAPagar;
import Classes.DateTime;
import Classes.Empresa;
import Classes.Fornecedor;
import Classes.ItemCompra;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Vinicius
 */
public class JDialogPagamentoCP extends javax.swing.JDialog {

    /**
     * Creates new form JDialogPagamentoCP
     */
    private String CNPJ;
    private int CodProd, Quant;
    private float CP_Total; // armazena total da venda e compra respectivamente
    
    public JDialogPagamentoCP(javax.swing.JDialog parent, boolean modal, String CNPJ, int CodProd, int Quant, float CP_Total) {
        super(parent, modal);
        initComponents();

        jComboBoxCP_Parcelas.setEnabled(false);
        jListCP_Parcelas.setEnabled(false);
        jButtonCP_FinalizarParcelas.setEnabled(false);

        // minerando as abas
        jTabbedPaneCP_Pagamento.setEnabledAt(1, false);
        jTabbedPaneCP_Pagamento.setSelectedIndex(0);


        jTextFieldCP_Valor.setEnabled(false);
        jLabelCP_Total.setText("" + CP_Total);
        jButtonCP_FinalizarPagVista.setEnabled(false);

        this.CNPJ = CNPJ;
        this.CodProd = CodProd;
        this.Quant = Quant;
        this.CP_Total = CP_Total;
        System.out.println("CNPJ: "+CNPJ);
    }
    
     public JDialogPagamentoCP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTabbedPaneCP_Pagamento.setEnabledAt(0, false);
        jButtonCP_FinalizarPagamento.setEnabled(false);
        jTabbedPaneCP_Pagamento.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneCP_Pagamento = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCP_Parcelas = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxCP_Parcelas = new javax.swing.JComboBox();
        jButtonCP_FinalizarParcelas = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabelAviso1 = new javax.swing.JLabel();
        jTextFieldCP_Valor = new javax.swing.JTextField();
        jButtonCP_FinalizarPagVista = new javax.swing.JButton();
        jComboBoxCP_Escolha = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabelCP_Total = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabelCP_Valor = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelCP_DataV = new javax.swing.JLabel();
        jLabelCP_Status = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelCP_NParcela = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabelCP_TrocoP = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabelCP_AvisoP = new javax.swing.JLabel();
        jTextFieldCP_ValorP = new javax.swing.JTextField();
        jButtonCP_FinalizarPagamento = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButtonCP_Localizar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldCP_CodParcela = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldCP_CodCompra = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabelCP_Fornecedor = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabelCP_Prestantes = new javax.swing.JLabel();
        jLabelCP_QtdParcela = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma de Pagamento");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Parcelado"));

        jScrollPane2.setViewportView(jListCP_Parcelas);

        jLabel17.setText("Numero de parcelas");

        jComboBoxCP_Parcelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jButtonCP_FinalizarParcelas.setText("Finalizar");
        jButtonCP_FinalizarParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCP_FinalizarParcelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCP_Parcelas, 0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCP_FinalizarParcelas)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxCP_Parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButtonCP_FinalizarParcelas)
                .addContainerGap())
        );

        jLabel18.setText("Forma de pagamento:");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "À Vista"));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Valor pago: R$");

        jLabelAviso1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelAviso1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jTextFieldCP_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCP_ValorActionPerformed(evt);
            }
        });
        jTextFieldCP_Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCP_ValorKeyReleased(evt);
            }
        });

        jButtonCP_FinalizarPagVista.setText("Finalizar");
        jButtonCP_FinalizarPagVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCP_FinalizarPagVistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCP_Valor)
                            .addComponent(jButtonCP_FinalizarPagVista)))
                    .addComponent(jLabelAviso1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabelAviso1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldCP_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButtonCP_FinalizarPagVista)
                .addContainerGap())
        );

        jComboBoxCP_Escolha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione forma de pagamento", "À vista", "Parcelado" }));
        jComboBoxCP_Escolha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxCP_EscolhaMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCP_EscolhaMouseClicked(evt);
            }
        });
        jComboBoxCP_Escolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCP_EscolhaActionPerformed(evt);
            }
        });
        jComboBoxCP_Escolha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBoxCP_EscolhaKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Valor da compra:  R$");

        jLabelCP_Total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCP_Total.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCP_Total.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCP_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCP_Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCP_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBoxCP_Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPaneCP_Pagamento.addTab("Forma de pagamento", jPanel9);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Parcela"));

        jLabelCP_Valor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setText("Valor:");

        jLabelCP_DataV.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCP_Status.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setText("Status Parcela:");

        jLabel24.setText("Data vencimento:");

        jLabel25.setText("Numero da Parcela:");

        jLabelCP_NParcela.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)))
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCP_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCP_Valor, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabelCP_DataV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCP_NParcela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabelCP_DataV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCP_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabelCP_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCP_NParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Efetuar pagamento"));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Valor pago: R$");

        jLabelCP_TrocoP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCP_TrocoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Troco:       R$");

        jLabelCP_AvisoP.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCP_AvisoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jTextFieldCP_ValorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCP_ValorPActionPerformed(evt);
            }
        });
        jTextFieldCP_ValorP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCP_ValorPKeyReleased(evt);
            }
        });

        jButtonCP_FinalizarPagamento.setText("Finalizar");
        jButtonCP_FinalizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCP_FinalizarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabelCP_AvisoP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCP_FinalizarPagamento))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addComponent(jLabelCP_TrocoP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCP_ValorP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabelCP_AvisoP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldCP_ValorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCP_TrocoP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCP_FinalizarPagamento)
                .addContainerGap())
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCP_Localizar.setText("Localizar");
        jButtonCP_Localizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCP_LocalizarActionPerformed(evt);
            }
        });

        jLabel28.setText("Codigo da compra:");

        jLabel29.setText("Codigo da parcela:");

        jLabel30.setText("Fornecedor:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCP_CodCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel29)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldCP_CodParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCP_Fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCP_Localizar)))
                .addGap(16, 16, 16))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldCP_CodParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCP_CodCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCP_Localizar)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelCP_Fornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Quantidades"));

        jLabelCP_Prestantes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCP_QtdParcela.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel31.setText("Parcelas restantes:");

        jLabel32.setText("Qtd Parcelas:");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCP_Prestantes, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabelCP_QtdParcela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabelCP_QtdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCP_Prestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPaneCP_Pagamento.addTab("Efetuar pagamento", jPanel12);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCP_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCP_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCP_FinalizarParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCP_FinalizarParcelasActionPerformed
        boolean Conf1 = false, Conf2 = true;

        int Parcelas = Integer.parseInt("" + jComboBoxCP_Parcelas.getSelectedItem());
        DateTime Dt = new DateTime();
        float Pl = CP_Total / Parcelas;

        // Salvando em contas a receber
        ContasAPagar Cp = new ContasAPagar();
        Cp.setCNPJFornecedor(CNPJ);
        Cp.setData(Dt.GetDateString());
        Cp.setQtdParcelas(Parcelas);
        Cp.setValorCompra(CP_Total);

        if (Cp.Salvar()) {
            Conf1 = true;
        } else {
            Conf2 = false;
        }
        //

        //Salvando os itemvendido
        ItemCompra I = new ItemCompra();
        Cp.ExisteCod(); // busca o ultimo codigo da venda
        I.setCodConta(Cp.getCodConta());
        I.setCodProduto(CodProd);
        I.setQuantidade(Quant);

        if (I.Salvar()) {
            Conf1 = true;
        } else {
            Conf2 = false;
        }

        // Salvando as parcelas
        Cp.ExisteCod(); // busca o ultimo codigo salvo, que é o da compra realizada
        Cp.setCodConta(Cp.getCodConta());
        DefaultListModel Model = new DefaultListModel();
        String D;
        for (int i = 1; i <= Parcelas; i++) {
            D = "" + Dt.SomarMes(i);
            Model.addElement("" + i + "º  " + D + " ..... R$ " + Pl);
            Cp.setCodParcela(i);
            Cp.setStatus(false);
            Cp.setDataPrevista(D);
            Cp.setValorParcela(Pl);

            if (Cp.SalvarPacelas()) {
                Conf1 = true;
            } else {
                Conf2 = false;
            }
        }
        jListCP_Parcelas.setModel(Model);// Mostra as parcelas no Jlist
        //

        //Segunda verificação: se não houver erro nas parcelas salva como debito da Empresa
        if (Conf1 && Conf2) {

            // salvando debito da empresa
            Empresa E = new Empresa();
            E.Pesquisa();

            if (E.EditarDebito(E.getCNPJ(), CP_Total)) {
                Conf1 = true;
            } else {
                Conf2 = false;
            }
            //

            //Terceira verificação: se não houver erro debito, finalizar
            if (Conf1 && Conf2) {
                JOptionPane.showMessageDialog(this, "Compra Finalizada com sucesso\n"
                    + "Codigo da Compra: " + Cp.getCodConta() + ",\nNumero de Parcelas: " + Parcelas + ".");
            } else {
                JOptionPane.showMessageDialog(this, "Error: Ao finalizar Compra");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error: Ao finalizar Compra");
        }

        // Bloqueando butoes
        jTextFieldCP_Valor.setEnabled(false);
        jButtonCP_FinalizarPagVista.setEnabled(false);
        jComboBoxCP_Parcelas.setEnabled(false);
        jButtonCP_FinalizarParcelas.setEnabled(false);
        jComboBoxCP_Escolha.setEnabled(false);
        //
    }//GEN-LAST:event_jButtonCP_FinalizarParcelasActionPerformed

    private void jTextFieldCP_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCP_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCP_ValorActionPerformed

    private void jTextFieldCP_ValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCP_ValorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCP_ValorKeyReleased

    private void jButtonCP_FinalizarPagVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCP_FinalizarPagVistaActionPerformed
        Empresa E = new Empresa();

        E.Pesquisa();
        E.setCNPJ(E.getCNPJ());
        E.setSaldo(E.getSaldo() - CP_Total);
        if (E.EditarSaldo()) {
            JOptionPane.showMessageDialog(this, "Compra Finalizada com sucesso");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ERRO: Compra não Finalizada");
        }
    }//GEN-LAST:event_jButtonCP_FinalizarPagVistaActionPerformed

    private void jComboBoxCP_EscolhaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCP_EscolhaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCP_EscolhaMouseReleased

    private void jComboBoxCP_EscolhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCP_EscolhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCP_EscolhaMouseClicked

    private void jComboBoxCP_EscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCP_EscolhaActionPerformed
        String Escolha = "" + jComboBoxCP_Escolha.getSelectedItem();
        if (Escolha.equals("À vista")) {
            jTextFieldCP_Valor.setEnabled(true);
            jTextFieldCP_Valor.setText("" + CP_Total);
            jButtonCP_FinalizarPagVista.setEnabled(true);

            jComboBoxCP_Parcelas.setEnabled(false);
            jListCP_Parcelas.setEnabled(false);
            jButtonCP_FinalizarParcelas.setEnabled(false);
        } else if (Escolha.equals("Parcelado")) {
            jTextFieldCP_Valor.setEnabled(false);
            jButtonCP_FinalizarPagVista.setEnabled(false);

            jComboBoxCP_Parcelas.setEnabled(true);
            jListCP_Parcelas.setEnabled(true);
            jButtonCP_FinalizarParcelas.setEnabled(true);
        } else {
            jTextFieldCP_Valor.setEnabled(false);
            jButtonCP_FinalizarPagVista.setEnabled(false);

            jComboBoxCP_Parcelas.setEnabled(false);
            jListCP_Parcelas.setEnabled(false);
            jButtonCP_FinalizarParcelas.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxCP_EscolhaActionPerformed

    private void jComboBoxCP_EscolhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxCP_EscolhaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCP_EscolhaKeyReleased

    private void jTextFieldCP_ValorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCP_ValorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCP_ValorPActionPerformed

    private void jTextFieldCP_ValorPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCP_ValorPKeyReleased
        float Valor, VPagar;

        VPagar = Float.parseFloat(jLabelCP_Valor.getText());
        try {
            jLabelCP_AvisoP.setText("");
            Valor = Float.parseFloat(jTextFieldCP_ValorP.getText());
            if ((Valor - VPagar) < 0) {
                jLabelCP_TrocoP.setText("Insuficiente");
                jButtonCP_FinalizarPagamento.setEnabled(false);
            } else {
                jLabelCP_TrocoP.setText("" + (Valor - VPagar));
                jButtonCP_FinalizarPagamento.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            jLabelCP_AvisoP.setText("Somente Numeros");
            jButtonCP_FinalizarPagamento.setEnabled(false);
            jTextFieldCP_ValorP.setText("");
        }
    }//GEN-LAST:event_jTextFieldCP_ValorPKeyReleased

    private void jButtonCP_FinalizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCP_FinalizarPagamentoActionPerformed
        Empresa E = new Empresa();
        E.Pesquisa();
        E.setSaldo(E.getSaldo() - Float.parseFloat(jLabelCP_Valor.getText())); //diminui saldo da empresa
        //E.setValorPagar(E.getValorPagar() - Float.parseFloat(jLabelCP_Valor.getText()));
        E.EditarDebito(E.getCNPJ(), (- Float.parseFloat(jLabelCP_Valor.getText())));// diminui valor a pagar
        E.setCNPJ(E.getCNPJ());
        if (E.EditarSaldo()) {
            ContasAPagar Cp = new ContasAPagar();
            Cp.PagarParcelas(Integer.parseInt(jTextFieldCP_CodCompra.getText()), Integer.parseInt(jTextFieldCP_CodParcela.getText()));
            JOptionPane.showMessageDialog(this, "Pagamento efetuado com sucesso");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ERRO: Pagamento não Finalizado");
        }
    }//GEN-LAST:event_jButtonCP_FinalizarPagamentoActionPerformed

    private void jButtonCP_LocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCP_LocalizarActionPerformed
        ContasAPagar Cp = new ContasAPagar();
        if (Cp.BuscaParcela(Integer.parseInt(jTextFieldCP_CodCompra.getText()), Integer.parseInt(jTextFieldCP_CodParcela.getText()))) {
            jTextFieldCP_ValorP.setEnabled(true);
            jLabelCP_DataV.setText(Cp.getDataPrevista());
            jLabelCP_Valor.setText("" + Cp.getValorParcela());

            //Mostrar o nome do cliente
            Fornecedor F = new Fornecedor();
            F.setCNPJ(Cp.getCNPJFornecedor());
            F.PesquisaPorCNPJ();
            jLabelCP_Fornecedor.setText(F.getRazaoSocial());
            if (Cp.isStatus()) {
                jLabelCP_Status.setText("Pagada");
                jTextFieldCP_ValorP.setEnabled(false);
            } else {
                jLabelCP_Status.setText("À pagar");
                jTextFieldCP_ValorP.setEnabled(true);
            }
            jLabelCP_NParcela.setText("" + Integer.parseInt(jTextFieldCP_CodParcela.getText()));
            jLabelCP_QtdParcela.setText("" + Cp.getQtdParcelas());
            jLabelCP_Prestantes.setText("" + Cp.getParcelaPendentes());
        } else {
            jTextFieldCP_ValorP.setEnabled(false);
            JOptionPane.showMessageDialog(null, "A uma conta anterior à se pagar");
        }
    }//GEN-LAST:event_jButtonCP_LocalizarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPagamentoCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPagamentoCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPagamentoCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPagamentoCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPagamentoCP dialog = new JDialogPagamentoCP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCP_FinalizarPagVista;
    private javax.swing.JButton jButtonCP_FinalizarPagamento;
    private javax.swing.JButton jButtonCP_FinalizarParcelas;
    private javax.swing.JButton jButtonCP_Localizar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxCP_Escolha;
    private javax.swing.JComboBox jComboBoxCP_Parcelas;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabelAviso1;
    private javax.swing.JLabel jLabelCP_AvisoP;
    private javax.swing.JLabel jLabelCP_DataV;
    private javax.swing.JLabel jLabelCP_Fornecedor;
    private javax.swing.JLabel jLabelCP_NParcela;
    private javax.swing.JLabel jLabelCP_Prestantes;
    private javax.swing.JLabel jLabelCP_QtdParcela;
    private javax.swing.JLabel jLabelCP_Status;
    private javax.swing.JLabel jLabelCP_Total;
    private javax.swing.JLabel jLabelCP_TrocoP;
    private javax.swing.JLabel jLabelCP_Valor;
    private javax.swing.JList jListCP_Parcelas;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneCP_Pagamento;
    private javax.swing.JTextField jTextFieldCP_CodCompra;
    private javax.swing.JTextField jTextFieldCP_CodParcela;
    private javax.swing.JTextField jTextFieldCP_Valor;
    private javax.swing.JTextField jTextFieldCP_ValorP;
    // End of variables declaration//GEN-END:variables
}
