/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Fornecedor;
import Classes.Produto;
import Classes.ProdutoFornecido;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriela
 */
public class JDialogEstoque extends javax.swing.JDialog {

    /**
     * Creates new form JDialogVizualizarProduto
     */
    public JDialogEstoque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Produto P = new Produto();
        P.carregaTabela(jTableProduto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPesquisarNome = new javax.swing.JTextField();
        jTextFieldPesquisarCodigo = new javax.swing.JTextField();
        jButtonLocalizarCodigo = new javax.swing.JButton();
        jButtonPesquisarDescricao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonRetirar = new javax.swing.JButton();
        jButtonComprar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldRazaoFornecedor = new javax.swing.JTextField();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisa"));
        jPanel1.setForeground(new java.awt.Color(51, 0, 255));

        jLabel1.setText("Nome:");

        jLabel2.setText("Código:");

        jTextFieldPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarNomeActionPerformed(evt);
            }
        });
        jTextFieldPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarNomeKeyReleased(evt);
            }
        });

        jTextFieldPesquisarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarCodigoKeyReleased(evt);
            }
        });

        jButtonLocalizarCodigo.setText("Localizar");
        jButtonLocalizarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarCodigoActionPerformed(evt);
            }
        });

        jButtonPesquisarDescricao.setText("Localizar");
        jButtonPesquisarDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarDescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisarDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPesquisarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLocalizarCodigo)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLocalizarCodigo)
                    .addComponent(jButtonPesquisarDescricao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Produtos"));

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Valor Unitário", "Disponiveis", "Estoque Min."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoMouseClicked(evt);
            }
        });
        jTableProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduto);
        jTableProduto.getColumnModel().getColumn(0).setMinWidth(80);
        jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableProduto.getColumnModel().getColumn(0).setMaxWidth(80);
        jTableProduto.getColumnModel().getColumn(2).setMinWidth(80);
        jTableProduto.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableProduto.getColumnModel().getColumn(2).setMaxWidth(80);
        jTableProduto.getColumnModel().getColumn(3).setMinWidth(80);
        jTableProduto.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableProduto.getColumnModel().getColumn(3).setMaxWidth(80);
        jTableProduto.getColumnModel().getColumn(4).setMinWidth(80);
        jTableProduto.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableProduto.getColumnModel().getColumn(4).setMaxWidth(80);

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonRetirar.setText("Retirar");
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });

        jButtonComprar.setText("Comprar");
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRetirar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAtualizar)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonRetirar)
                    .addComponent(jButtonComprar))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações:"));

        jLabel14.setText("Fornecedor:");

        jTextFieldRazaoFornecedor.setEnabled(false);

        try {
            jFormattedTextFieldCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNPJ.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextFieldRazaoFornecedor)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldRazaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarNomeActionPerformed

    private void jTextFieldPesquisarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarNomeKeyReleased
        // TODO add your handling code here:
        Produto P = new Produto();
        P.setDescProduto("%" + jTextFieldPesquisarNome.getText() + "%");
        P.PesquisaTabelaDescricao(jTableProduto);
    }//GEN-LAST:event_jTextFieldPesquisarNomeKeyReleased

    private void jTextFieldPesquisarCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarCodigoKeyReleased
        // TODO add your handling code here:  
    }//GEN-LAST:event_jTextFieldPesquisarCodigoKeyReleased

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked
        // TODO add your handling code here:
        int cod = Integer.parseInt("" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 0));
        ProdutoFornecido PF = new ProdutoFornecido();
        PF.setCodProduto(cod);
        PF.PesquisaCodigoProduto();
        jFormattedTextFieldCNPJ.setText(PF.getCNPJFornecedor());
        Fornecedor F = new Fornecedor();
        F.setCNPJ(PF.getCNPJFornecedor());
        F.PesquisaPorCNPJ();
        jTextFieldRazaoFornecedor.setText(F.getRazaoSocial());
    }//GEN-LAST:event_jTableProdutoMouseClicked

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        Produto P = new Produto();
        P.carregaTabela(jTableProduto);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        if (jTableProduto.getSelectedRow() != -1) {
            new JDialogProdutoAlterar(this, true, Integer.parseInt("" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 0))).setVisible(true);
            Produto P = new Produto();
            P.carregaTabela(jTableProduto);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto");
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if (jTableProduto.getSelectedRow() != -1) {
            new JDialogProdutoExcluir(this, true, Integer.parseInt("" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 0))).setVisible(true);
            Produto P = new Produto();
            P.carregaTabela(jTableProduto);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed
        // TODO add your handling code here:
        if (jTableProduto.getSelectedRow() != -1) {
            int Qtd;
            Qtd = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade de produtos retirados"));
            Produto P = new Produto();
            P.setCodProduto(Integer.parseInt("" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 0)));
            P.PesquisaCodigo();

            if ((P.getQtdProduto() - Qtd) > 0) {
                P.setQtdProduto(P.getQtdProduto() - Qtd);
                P.Alterar();
                P.carregaTabela(jTableProduto);
            } else {
                JOptionPane.showMessageDialog(this, "Estoque insuficiente");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto");
        }
    }//GEN-LAST:event_jButtonRetirarActionPerformed

    private void jButtonLocalizarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarCodigoActionPerformed
        // TODO add your handling code here:
        Produto P = new Produto();
        P.setCodProduto(Integer.parseInt(jTextFieldPesquisarCodigo.getText()));
        P.PesquisaTabelaCodigo(jTableProduto);
    }//GEN-LAST:event_jButtonLocalizarCodigoActionPerformed

    private void jButtonPesquisarDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarDescricaoActionPerformed
        // TODO add your handling code here:
        Produto P = new Produto();
        P.setDescProduto("%" + jTextFieldPesquisarNome.getText() + "%");
        P.PesquisaTabelaDescricao(jTableProduto);
    }//GEN-LAST:event_jButtonPesquisarDescricaoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
        // TODO add your handling code here:
        if (jTableProduto.getSelectedRow() != -1) {
            int cod = Integer.parseInt("" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 0));
            Float Valor = Float.parseFloat("" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 2));
            ProdutoFornecido PF = new ProdutoFornecido();
            PF.setCodProduto(cod);
            PF.PesquisaCodigoProduto();
            Fornecedor F = new Fornecedor();
            F.setCNPJ(PF.getCNPJFornecedor());
            F.PesquisaPorCNPJ();
            jTextFieldRazaoFornecedor.setText(F.getRazaoSocial());
            int quant = Integer.parseInt(JOptionPane.showInputDialog("Entre com quantidade:"));
            new JDialogPagamentoCP(this, true, PF.getCNPJFornecedor(), cod,quant, quant*Valor).setVisible(true);
            Produto P = new Produto();
            P.setCodProduto(cod);
            P.PesquisaCodigo();
            P.setQtdProduto(P.getQtdProduto() + quant);
            P.Alterar();
            Produto.carregaTabela(jTableProduto);
            JOptionPane.showMessageDialog(this, "Estoque Atualizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto");
        }
    }//GEN-LAST:event_jButtonComprarActionPerformed

    private void jTableProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProdutoKeyReleased
        // TODO add your handling code here:
        int cod = Integer.parseInt("" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 0));
        ProdutoFornecido PF = new ProdutoFornecido();
        PF.setCodProduto(cod);
        PF.PesquisaCodigoProduto();
        jFormattedTextFieldCNPJ.setText(PF.getCNPJFornecedor());
        Fornecedor F = new Fornecedor();
        F.setCNPJ(PF.getCNPJFornecedor());
        F.PesquisaPorCNPJ();
        jTextFieldRazaoFornecedor.setText(F.getRazaoSocial());


    }//GEN-LAST:event_jTableProdutoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEstoque dialog = new JDialogEstoque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLocalizarCodigo;
    private javax.swing.JButton jButtonPesquisarDescricao;
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextFieldPesquisarCodigo;
    private javax.swing.JTextField jTextFieldPesquisarNome;
    private javax.swing.JTextField jTextFieldRazaoFornecedor;
    // End of variables declaration//GEN-END:variables
}
