/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Clientes;
import Classes.Vendedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Vinicius
 */
public class JDialogTConfirmação extends javax.swing.JDialog {

    /**
     * Creates new form JDialogTConfirmação
     */
    private String CPF, CNPJ, Tipo; // variavel tipo guardar o tipo de buscar (Cliente, Vendedor, Fornecedor)
    private int Cod;

    //construtor para Clientes
    public JDialogTConfirmação(javax.swing.JDialog parent, boolean modal, String CPF, String N) {
        super(parent, modal);
        initComponents();
        Tipo = "Cliente";

        this.CPF = CPF;
        jLabelNome.setText(N);
    }

    //construtor para vendedor
    public JDialogTConfirmação(javax.swing.JDialog parent, boolean modal, int Cod, String N) {
        super(parent, modal);
        initComponents();
        Tipo = "Vendedor";

        this.Cod = Cod;
        jLabelNome.setText(N);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jButtonSim = new javax.swing.JButton();
        jButtonNao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confimação");

        jLabel1.setText("Deseja realmente Excluir:");

        jLabelNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSim.setText("Sim");
        jButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimActionPerformed(evt);
            }
        });

        jButtonNao.setText("Não");
        jButtonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButtonSim)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonNao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSim)
                    .addComponent(jButtonNao))
                .addGap(27, 27, 27))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-352)/2, (screenSize.height-153)/2, 352, 153);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimActionPerformed
        if (Tipo.equals("Cliente")) {
            Clientes C = new Clientes();
            if (C.ExcluirCliente(CPF)) {
                JOptionPane.showMessageDialog(this, "Cliente excluido com sucesso");
                dispose();
            }
        }else if(Tipo.equals("Vendedor")){
            Vendedor V = new Vendedor();
            if (V.ExcluirVendedor(Cod)) {
                JOptionPane.showMessageDialog(this, "Vendedor excluido com sucesso");
                dispose();
            }
        }else{
            //fornecedor
        }
    }//GEN-LAST:event_jButtonSimActionPerformed

    private void jButtonNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNaoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonNaoActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
     /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     *
     try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(JDialogTConfirmação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(JDialogTConfirmação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(JDialogTConfirmação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(JDialogTConfirmação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the dialog */
    /*  java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     JDialogTConfirmação dialog = new JDialogTConfirmação(new javax.swing.JDialog(), true,);
     dialog.addWindowListener(new java.awt.event.WindowAdapter() {
     @Override
     public void windowClosing(java.awt.event.WindowEvent e) {
     System.exit(0);
     }
     });
     dialog.setVisible(true);
     }
     });
     }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNao;
    private javax.swing.JButton jButtonSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNome;
    // End of variables declaration//GEN-END:variables
}
