package Telas;

import Classes.Clientes;
import Classes.Vendedor;
import javax.swing.JOptionPane;
import telas.JDialogProdutoCadastrar;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Diorgenes
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEstoque = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCadastroClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonCadastraVendedor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtoCompras = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButtonPagamento = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadastrarClientes = new javax.swing.JMenuItem();
        jMenuItemCadastrarFornecedor = new javax.swing.JMenuItem();
        jMenuItemCadastrarProduto = new javax.swing.JMenuItem();
        jMenuItemCadastrarVendedor = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuPesquisa = new javax.swing.JMenu();
        jMenuItemPesquisaClientes = new javax.swing.JMenuItem();
        jMenuItemPesquisaFornecedor = new javax.swing.JMenuItem();
        jMenuItemPesquisaProduto = new javax.swing.JMenuItem();
        jMenuItemPesquisaVendedor = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemEditarClientes = new javax.swing.JMenuItem();
        jMenuItemEditarFornecedor = new javax.swing.JMenuItem();
        jMenuItemEditarProduto = new javax.swing.JMenuItem();
        jMenuItemEditarVendedor = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemContaReceber = new javax.swing.JMenuItem();
        jMenuItemContasPagar = new javax.swing.JMenuItem();
        jMenuEstoque = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemdataVenda = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();

        jButtonEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/48/box_download-48.png"))); // NOI18N
        jButtonEstoque.setToolTipText("Entrar no Estoque");
        jButtonEstoque.setFocusable(false);
        jButtonEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstoqueActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Informação Gerencial - SIO");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jToolBar1.setRollover(true);

        jButtonCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/48/user_add2_48.png"))); // NOI18N
        jButtonCadastroClientes.setToolTipText("Cadastro de Clientes");
        jButtonCadastroClientes.setFocusable(false);
        jButtonCadastroClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastroClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadastroClientes);
        jToolBar1.add(jSeparator1);

        jButtonCadastraVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/48/personal_loan-48.png"))); // NOI18N
        jButtonCadastraVendedor.setToolTipText("Cadastro de Vendedor");
        jButtonCadastraVendedor.setFocusable(false);
        jButtonCadastraVendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastraVendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastraVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraVendedorActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadastraVendedor);
        jToolBar1.add(jSeparator2);

        jButtoCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/48/Trolley-48.png"))); // NOI18N
        jButtoCompras.setToolTipText("realizar venda");
        jButtoCompras.setFocusable(false);
        jButtoCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtoCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtoCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoComprasActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtoCompras);
        jToolBar1.add(jSeparator5);

        jButtonPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/48/Pagamento.png"))); // NOI18N
        jButtonPagamento.setToolTipText("Efetuar pagamento");
        jButtonPagamento.setFocusable(false);
        jButtonPagamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPagamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonPagamento);
        jToolBar1.add(jSeparator4);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/48/logout-48.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair do Sistema");
        jButtonSair.setFocusable(false);
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSair);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Background/Background.png"))); // NOI18N

        jMenuCadastros.setText("Cadastros");

        jMenuItemCadastrarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadastrarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/user_add-20.png"))); // NOI18N
        jMenuItemCadastrarClientes.setMnemonic('c');
        jMenuItemCadastrarClientes.setText("Clientes");
        jMenuItemCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarClientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastrarClientes);

        jMenuItemCadastrarFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadastrarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/enterprise-16.png"))); // NOI18N
        jMenuItemCadastrarFornecedor.setMnemonic('f');
        jMenuItemCadastrarFornecedor.setText("Fornecedor");
        jMenuItemCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastrarFornecedor);

        jMenuItemCadastrarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/bag_shopping-16.png"))); // NOI18N
        jMenuItemCadastrarProduto.setMnemonic('p');
        jMenuItemCadastrarProduto.setText("Produto");
        jMenuItemCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarProdutoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastrarProduto);

        jMenuItemCadastrarVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadastrarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/personal_loan-16.png"))); // NOI18N
        jMenuItemCadastrarVendedor.setMnemonic('v');
        jMenuItemCadastrarVendedor.setText("Vendedor");
        jMenuItemCadastrarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarVendedorActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastrarVendedor);

        jMenuItem2.setText("Empresa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem2);

        jMenuBar1.add(jMenuCadastros);

        jMenuPesquisa.setText("Pesquisas");

        jMenuItemPesquisaClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemPesquisaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/1370905095_user_profile_edit.png"))); // NOI18N
        jMenuItemPesquisaClientes.setMnemonic('c');
        jMenuItemPesquisaClientes.setText("Clientes");
        jMenuItemPesquisaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisaClientesActionPerformed(evt);
            }
        });
        jMenuPesquisa.add(jMenuItemPesquisaClientes);

        jMenuItemPesquisaFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemPesquisaFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/1370905271_user_half_edit.png"))); // NOI18N
        jMenuItemPesquisaFornecedor.setMnemonic('f');
        jMenuItemPesquisaFornecedor.setText("Fornecedor");
        jMenuItemPesquisaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisaFornecedorActionPerformed(evt);
            }
        });
        jMenuPesquisa.add(jMenuItemPesquisaFornecedor);

        jMenuItemPesquisaProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/1370907049_new-24.png"))); // NOI18N
        jMenuItemPesquisaProduto.setMnemonic('p');
        jMenuItemPesquisaProduto.setText("Produto");
        jMenuItemPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisaProdutoActionPerformed(evt);
            }
        });
        jMenuPesquisa.add(jMenuItemPesquisaProduto);

        jMenuItemPesquisaVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemPesquisaVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/1370907123_group_full_edit.png"))); // NOI18N
        jMenuItemPesquisaVendedor.setMnemonic('v');
        jMenuItemPesquisaVendedor.setText("Vendedor");
        jMenuItemPesquisaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisaVendedorActionPerformed(evt);
            }
        });
        jMenuPesquisa.add(jMenuItemPesquisaVendedor);

        jMenuItem3.setText("Dados Empresa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuPesquisa.add(jMenuItem3);

        jMenuBar1.add(jMenuPesquisa);

        jMenuEditar.setText("Editar/Excluir");

        jMenuItemEditarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemEditarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/1370905095_user_profile_edit.png"))); // NOI18N
        jMenuItemEditarClientes.setMnemonic('c');
        jMenuItemEditarClientes.setText("Clientes");
        jMenuItemEditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarClientesActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemEditarClientes);

        jMenuItemEditarFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemEditarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/1370905271_user_half_edit.png"))); // NOI18N
        jMenuItemEditarFornecedor.setMnemonic('f');
        jMenuItemEditarFornecedor.setText("Fornecedor");
        jMenuItemEditarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarFornecedorActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemEditarFornecedor);

        jMenuItemEditarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/1370907049_new-24.png"))); // NOI18N
        jMenuItemEditarProduto.setMnemonic('p');
        jMenuItemEditarProduto.setText("Produto");
        jMenuItemEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarProdutoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemEditarProduto);

        jMenuItemEditarVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemEditarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/1370907123_group_full_edit.png"))); // NOI18N
        jMenuItemEditarVendedor.setMnemonic('v');
        jMenuItemEditarVendedor.setText("Vendedor");
        jMenuItemEditarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarVendedorActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemEditarVendedor);

        jMenuBar1.add(jMenuEditar);

        jMenu1.setText("Pagamentos");

        jMenuItemContaReceber.setText("Contas a Receber");
        jMenuItemContaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContaReceberActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemContaReceber);

        jMenuItemContasPagar.setText("Contas a Pagar");
        jMenuItemContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContasPagarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemContasPagar);

        jMenuBar1.add(jMenu1);

        jMenuEstoque.setText("Estoque");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/box_download-16.png"))); // NOI18N
        jMenuItem1.setText("Acessar Estoque");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuEstoque.add(jMenuItem1);

        jMenuBar1.add(jMenuEstoque);

        jMenuRelatorio.setText("Relarios");

        jMenuItemdataVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemdataVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16/Relatorio venda.png"))); // NOI18N
        jMenuItemdataVenda.setText("Relatorio venda");
        jMenuItemdataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemdataVendaActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemdataVenda);

        jMenuBar1.add(jMenuRelatorio);

        jMenuAjuda.setText("Ajuda");
        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-639)/2, (screenSize.height-458)/2, 639, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarFornecedorActionPerformed
        // TODO add your handling code here:
        new JDialogFornecedorCadastrar(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarFornecedorActionPerformed

    private void jMenuItemCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        new JDialogProdutoCadastrar(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarProdutoActionPerformed

    private void jMenuItemEditarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarFornecedorActionPerformed
        // TODO add your handling code here:
        new JDialogFornecedorEdicaodeDados(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarFornecedorActionPerformed

    private void jMenuItemEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarProdutoActionPerformed
        // TODO add your handling code here:
        new JDialogProdutoEdicaodeDados(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new JDialogEstoque(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuItemCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClientesActionPerformed
        new JDialogCliente(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarClientesActionPerformed

    private void jMenuItemCadastrarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarVendedorActionPerformed
        new JDialogVendedor(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarVendedorActionPerformed

    private void jMenuItemEditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarClientesActionPerformed
        new JDialogClientesEdicaoDeDados(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarClientesActionPerformed

    private void jMenuItemEditarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarVendedorActionPerformed
        new JDialogVendedorEdicaoDados(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarVendedorActionPerformed

    private void jButtonEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstoqueActionPerformed
        new JDialogEstoque(this, true).setVisible(true);
    }//GEN-LAST:event_jButtonEstoqueActionPerformed

    private void jButtonCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroClientesActionPerformed
        new JDialogCliente(this, true).setVisible(true);
    }//GEN-LAST:event_jButtonCadastroClientesActionPerformed

    private void jButtonCadastraVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraVendedorActionPerformed
        new JDialogVendedor(this, true).setVisible(true);
    }//GEN-LAST:event_jButtonCadastraVendedorActionPerformed

    private void jMenuItemPesquisaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisaClientesActionPerformed
        new JDialogClientePesquisa(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisaClientesActionPerformed

    private void jMenuItemPesquisaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisaFornecedorActionPerformed
        new JDialogFornecedorPesquisa(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisaFornecedorActionPerformed

    private void jMenuItemPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisaProdutoActionPerformed
        new JDialogProdutoPesquisa(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisaProdutoActionPerformed

    private void jMenuItemPesquisaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisaVendedorActionPerformed
        new JDialogVendedorPesquisa(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisaVendedorActionPerformed

    private void jButtoComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoComprasActionPerformed
        boolean N = true, P = true;
        int CodVendedor = 0;
        Vendedor V = new Vendedor();
        Clientes C = new Clientes();
        do {
            N = true;
            String s = JOptionPane.showInputDialog(this, "Entre com o Codigo do Vendedor:");
            if (s == null) {
                P = false;
            } else if (s.equals("")) {
                N = false;
            } else {
                try {
                    CodVendedor = Integer.parseInt(s);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Campo so aceita numeros.");
                }
                if (!V.PesquisaVendedor(CodVendedor)) {
                    JOptionPane.showMessageDialog(this, "Vendedor não encontrado.\nCodigo invalido ou Vendedor não está cadastrado.");
                    N = false;
                }
            }
        } while (!N);

        String T = null;
        String CPFCliente = null;

        if (P) {
            do {
                N = true;
                try {
                    do {

                        T = JOptionPane.showInputDialog(this, "Entre com o CPF do cliente");
                        if (T == null) {
                            P = false;
                        } else if (T.length() != 11) {
                            JOptionPane.showMessageDialog(this, "Quantidade de digito invalida ");
                        }

                    } while (T.length() != 11);

                    // Transforma para o formato q esta salvo no banco de dados
                    CPFCliente = T.substring(0, 3) + "." + T.substring(3, 6) + "." + T.substring(6, 9) + "-" + T.substring(9, 11);
                } catch (Exception e) {
                }                //

                if (!C.pesquisa(CPFCliente)) {
                    JOptionPane.showMessageDialog(this, "Cliente não encontrado não encontrado.\nCPF invalido ou cliente não está cadastrado.");
                    N = false;

                }
            } while (!N);
        }
        if (P) {
            new JDialogVenda(this, true, CodVendedor, CPFCliente, V.getNome(), C.getNome()).setVisible(true);
        }
    }//GEN-LAST:event_jButtoComprasActionPerformed

    private void jButtonPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagamentoActionPerformed
        new JDialogPagamentoCR(this, true).setVisible(true);
    }//GEN-LAST:event_jButtonPagamentoActionPerformed

    private void jMenuItemdataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemdataVendaActionPerformed
        new JDialogRelatorio(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemdataVendaActionPerformed

    private void jMenuItemContaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContaReceberActionPerformed
        new JDialogPagamentoCR(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemContaReceberActionPerformed

    private void jMenuItemContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContasPagarActionPerformed
        new JDialogPagamentoCP(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemContasPagarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new JDialogEmpresaCadastrar(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new JDialogEmpresa(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoCompras;
    private javax.swing.JButton jButtonCadastraVendedor;
    private javax.swing.JButton jButtonCadastroClientes;
    private javax.swing.JButton jButtonEstoque;
    private javax.swing.JButton jButtonPagamento;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuEstoque;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCadastrarClientes;
    private javax.swing.JMenuItem jMenuItemCadastrarFornecedor;
    private javax.swing.JMenuItem jMenuItemCadastrarProduto;
    private javax.swing.JMenuItem jMenuItemCadastrarVendedor;
    private javax.swing.JMenuItem jMenuItemContaReceber;
    private javax.swing.JMenuItem jMenuItemContasPagar;
    private javax.swing.JMenuItem jMenuItemEditarClientes;
    private javax.swing.JMenuItem jMenuItemEditarFornecedor;
    private javax.swing.JMenuItem jMenuItemEditarProduto;
    private javax.swing.JMenuItem jMenuItemEditarVendedor;
    private javax.swing.JMenuItem jMenuItemPesquisaClientes;
    private javax.swing.JMenuItem jMenuItemPesquisaFornecedor;
    private javax.swing.JMenuItem jMenuItemPesquisaProduto;
    private javax.swing.JMenuItem jMenuItemPesquisaVendedor;
    private javax.swing.JMenuItem jMenuItemdataVenda;
    private javax.swing.JMenu jMenuPesquisa;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
